export type Run = { id?: string; run_date: string; distance_km: number; moving_time_seconds: number; effort?: number | null; notes?: string | null; source?: string | null };
export type PlanWorkout = { week: number; day: string; type: string; title: string; detail: string; target: string };
export function pace(sec:number, km:number){ if(!sec||!km) return ''; const s=Math.round(sec/km); return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}/km`; }
export function secondsFromPace(p:string){ const [m,s]=p.split(':').map(Number); return (m||0)*60+(s||0); }
export function predict10k(runs:Run[]){ const recent=runs.slice().sort((a,b)=>b.run_date.localeCompare(a.run_date)).filter(r=>r.distance_km>=3).slice(0,8); if(!recent.length) return null; const preds=recent.map(r=>{ const t=r.moving_time_seconds*Math.pow(10/r.distance_km,1.06); return t; }); const avg=preds.reduce((a,b)=>a+b,0)/preds.length; return Math.round(avg); }
export function fitnessBand(pred:number|null){ if(!pred) return 'Log a few runs to estimate fitness.'; if(pred<=3000) return 'On sub-50 trajectory.'; if(pred<=3090) return 'Close. Consistent tempo work should bridge the gap.'; return 'Build aerobic volume first, then sharpen pace.'; }
export function generatePlan(startDate=new Date(), weeks=12):PlanWorkout[]{ const out:PlanWorkout[]=[]; for(let w=1;w<=weeks;w++){ const build=Math.min(w,8); const easy=5+Math.floor(build/2); const long=7+build; const tempo=Math.min(20+w*2,35); const reps=w<5?'6 × 400m':w<9?'5 × 800m':'4 × 1km'; out.push({week:w,day:'Tue',type:'Intervals',title:`${reps}`,detail:'Warm up 10 mins, run the reps controlled, jog recoveries, cool down 10 mins.',target:w<5?'4:40-4:50/km on reps':w<9?'4:45-4:55/km on reps':'4:50-5:00/km on reps'}); out.push({week:w,day:'Thu',type:'Tempo',title:`${tempo} min tempo`,detail:'Comfortably hard, not a race. You should finish feeling you could do a little more.',target:w<5?'5:20-5:30/km':w<9?'5:10-5:20/km':'5:00-5:12/km'}); out.push({week:w,day:'Sun',type:'Long easy',title:`${long} km easy`,detail:'Conversational pace. This is about endurance, not speed.',target:'6:00-6:45/km'}); if(w%4===0) out.push({week:w,day:'Sat',type:'Tune-up',title:'5k steady or parkrun',detail:'Use this to check progress, but avoid racing every time.',target:'Start around 5:15/km, progress if comfortable'}); }
 return out; }
export function nextAdvice(runs:Run[]){ const pred=predict10k(runs); const last=runs.slice().sort((a,b)=>b.run_date.localeCompare(a.run_date))[0]; const lines=[]; if(pred){ const m=Math.floor(pred/60), s=String(pred%60).padStart(2,'0'); lines.push(`Estimated current 10k: ${m}:${s}. ${fitnessBand(pred)}`); } else lines.push('Add recent runs to unlock predictions.'); if(last){ const p=pace(last.moving_time_seconds,last.distance_km); lines.push(`Latest run: ${last.distance_km} km at ${p}.`); if(last.effort && last.effort>=8) lines.push('That effort was high. Keep the next run genuinely easy.'); else lines.push('If you felt fresh, the next quality session can stay on plan.'); }
 return lines; }
